### ISSUE TITLE
Deploy fails

### ISSUE THREAD

**Issue by shinsaka** [AmazonConnectSalesforceIntegration/AmazonConnectSalesforceLambda#1]
Hello,

An error occurs in the following a step:

```
sfRealTimeQueueMetricsLoopJobStateMachine
```

The error message is:
```
Property validation failure: [Length of value for property {/StateMachineName} is greater than maximum allowed length {80}]
```

I'm not very familiar with it, I think caused by following line in template.yaml.

```
    StateMachineName: !Sub '${AWS::StackName}-sfRealTimeQueueMetricsLoopJobStateMachine'
```

Assuming "${AWS::StackName}" is "serverlessrepo-AmazonConnectSalesforceLambda",
StateMachineName is "serverlessrepo-AmazonConnectSalesforceLambda-sfRealTimeQueueMetricsLoopJobStateMachine", its length is over 80.

Thank you for the help.

**Comment by suhel1612** [comment]
Hi,
I am facing the same issue. Any resolution or work around please?

**Comment by AmazonConnectSalesforceIntegration** [comment]
This was due to long StackName. Please test with v4.0.1

**Comment by shinsaka** [comment]
it worked fine 😄
v4.0.1 fixed the issue, Thank you!
