### ISSUE TITLE
No Post Call Transcript Generated "Contact Analytics Transcript"

### ISSUE THREAD

**Issue by ember32** [AmazonConnectSalesforceIntegration/AmazonConnectSalesforceLambda#2]
Greetings,

I have this issue that Salesforce doesn't generate any transcription at all _(**Kindly see picture below)**_

![image](https://user-images.githubusercontent.com/48548753/70960699-b02d8300-20ba-11ea-80b2-32b2f4add927.png)

I hope you can help me with this one. 

Thank you in advance sir! 
Cheers

**Comment by shinsaka** [comment]
Sorry, I'm not sure. 🙇
